### PR TITLE
Add Airbnb, Uber, TripAdvisor, WeChat, Weixin, and WhatsApp

### PR DESCRIPTION
**Pull request by ahlee2326**

### CODE REVIEW

**Comment by devgru** [comment]
Why not add another two Uber colors, white and blue? IMHO it makes sense.

**Comment by reimertz** [comment]
I agree with @devgru, could you add the white and blue as well? Thanks for doing this!

**Comment by ahlee2326** [comment]
Updated, with more brand colors.

**Comment by reimertz** [comment]
Thanks again for doing this!

**Pull request merged**
