### PR TITLE
fix indented Sass variables

### PR DESCRIPTION
**Pull request by Grawl**

### CODE REVIEW

**Comment by Grawl** [comment]
And I think there is no need to have indented Sass version. you always can import `.sass` into `.scss` and vice versa. You can just delete it in next major or even minor release and no one will have a problem with it.

**Comment by reimertz** [comment]
could you rebase and then update your pr?

**Comment by Grawl** [comment]
I don't know how to rebase, sorry

**Comment by Grawl** [comment]
awesome

**Pull request closed without merging**
