### PR TITLE
Add University of Kentucky

### PR DESCRIPTION
**Pull request by sammarks**
Primary brand color: #005DAA
Web Standards: https://www.uky.edu/Graphics/WebGraphicStandards.pdf

### CODE REVIEW

**Comment by reimertz** [comment]
Awesome!
Could you please add it to /index.html as well?
just one more thing

**Comment by reimertz** [comment]
@sammarks  you there?

**Comment by sammarks** [comment]
Oops, didn't see this! Just pushed it.

**Comment by reimertz** [comment]
Awesome, thanks!

**Pull request merged**
