### PR TITLE
Add myworld brand color

### PR DESCRIPTION
**Pull request by gazay**
https://my.mail.ru/

### CODE REVIEW

**Comment by devgru** [comment]
This is Mail.ru brand color, not only myworld's. Second one is #ffa930.

Check http://corp.mail.ru/en/press/identity/#colors

**Comment by gazay** [comment]
Thank you, @devgru

**Comment by ai** [comment]
Any updates?

**Comment by reimertz** [comment]
Sorry guys, I will merge all the requests tonight. :D

**Comment by devgru** [comment]
@reimertz any updates? :-)

**Comment by reimertz** [comment]
Ok, I suck ass. But at last, I will bump the version on this tool. Thanks again for the patience.

**Pull request merged**
