### PR TITLE
Updated Salesforce

### PR DESCRIPTION
**Pull request by Dottenpixel**
Brand color per https://www.lightningdesignsystem.com/resources/tokens

### CODE REVIEW

**Comment by reimertz** [comment]
Thanks dotten
can you add the color in index.html and readme.md?

**Comment by reimertz** [comment]
@Dottenpixel you there?

**Comment by Dottenpixel** [comment]
Hi! sorry I missed your message here. I'm not sure what you mean by adding the color to index.html and readme. Isn't the `brandColors.js` file the single source for the color data?

**Comment by reimertz** [comment]
@Dottenpixel no worries at all! I merged it after I implemented a script that generates everything from `data/brandColors.js` so we're all good. :)

**Pull request merged**
