### PR TITLE
fix 2.0.0 scss file output

### PR DESCRIPTION
**Pull request by jonoshearman**
For some reason the dist/latest/ and dist/2.0.0 .scss files were built without semicolons to end each line.
Running `gulp dist` output the correct files, so the template works fine.
I've simply updated these files with the correctly rendered output

### CODE REVIEW

**Comment by reimertz** [comment]
Shit, thats bad. Could you also bump the version and run the script again so that I can publish this fix as 2.0.1?

**Comment by reimertz** [comment]
This is done by just bumping the version in `package.json` before running `gulp dist`

**Comment by jonoshearman** [comment]
there you go

**Comment by reimertz** [comment]
Thanks @jonoshearman, update now published as v2.0.1. ❤️

**Pull request merged**
